### ISSUE TITLE
Error on running application

### ISSUE THREAD

**Issue by hendisantika** [seongpyoHong/Spring-boot-CRUD#1]
I have clone your repo. But when I tried to run the application error occured.

```
***************************
APPLICATION FAILED TO START
***************************

Description:

Method springSecurityFilterChain in org.springframework.security.config.annotation.web.configuration.WebSecurityConfiguration required a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' that could not be found.

The following candidates were found but could not be injected:
        - Bean method 'clientRegistrationRepository' in 'OAuth2ClientRegistrationRepositoryConfiguration' not loaded because OAuth2 Clients Configured Condition registered clients is not available


Action:

Consider revisiting the entries above or defining a bean of type 'org.springframework.security.oauth2.client.registration.ClientRegistrationRepository' in your configuration.


> Task :bootRun FAILED
:bootRun (Thread[Execution worker for ':' Thread 5,5,main]) completed. Took 11.713 secs.

FAILURE: Build failed with an exception.

```

Any suggestions?
Thanks

**Comment by seongpyoHong** [comment]
I think this situation arose because the setting for oauth2 was not added to the repository. 
It is thought that adding the following settings to the `application.yml` will solve this problem.

```
spring.security.oauth2.client.registration.google.client-id=<client-id>
spring.security.oauth2.client.registration.google.client-secret =<cilent-secret>
spring.security.oauth2.client.registration.google.scope=profile, email
```

Thanks.

**Comment by hendisantika** [comment]
OOo.. Yeahhh..
You are right. Need to add those configuration.

Thanks @seongpyoHong

**Comment by Sunray8055** [comment]
server:
  port: 8085

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_security?createDatabaseIfNotExist=true&useSSL=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

security:
  oauth2:
    client:
      registration:
        google:
          client-id: 562873518516-j8tp1t97q7kl2vpv8a6b4uhlpct10jsr.apps.googleusercontent.com
          client-secret: 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
          scope :
            - email
            - profile
        github:
          client-id: ed1e84c160343a83a2a2
          client-secret: 6e53e64e329369566b499c8d32cdb80d5bc56cb2
          scope :
            - user
            - read
        facebook:
          client-id: 557916549658500
          client-secret: 8d691f230cd4dcaf02e6fa33bc149ec4
          scope:
            - email
            - public_profile






I am getting the same issue..
